name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-amd64
            artifact_name: chi
            target: linux_amd64
          - os: ubuntu-latest
            suffix: linux-arm64
            artifact_name: chi
            target: linux_arm64
          - os: ubuntu-latest
            suffix: linux-i386
            artifact_name: chi
            target: linux_i386
          - os: macos-latest
            suffix: darwin-arm64
            artifact_name: chi
            target: darwin_arm64
          - os: macos-latest
            suffix: darwin-amd64
            artifact_name: chi
            target: darwin_amd64
          - os: windows-latest
            suffix: windows-amd64
            artifact_name: chi.exe
            target: windows_amd64
          - os: windows-latest
            suffix: windows-i386
            artifact_name: chi.exe
            target: windows_i386

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          release: dev-2026-02

      - name: Build binary
        run: odin build src/ -out:${{ matrix.artifact_name }} -o:speed -target:${{ matrix.target }}

      - name: Rename binary for release
        run: mv ${{ matrix.artifact_name }} chi-${{ matrix.suffix }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: chi-${{ matrix.suffix }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
