name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-amd64
            artifact_name: chi
          - os: ubuntu-latest
            suffix: linux-arm64
            artifact_name: chi
          - os: ubuntu-latest
            suffix: linux-i386
            artifact_name: chi
          - os: macos-latest
            suffix: darwin-arm64
            artifact_name: chi
          - os: macos-latest
            suffix: darwin-amd64
            artifact_name: chi
          - os: windows-latest
            suffix: windows-amd64
            artifact_name: chi.exe
          - os: windows-latest
            suffix: windows-i386
            artifact_name: chi.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          version: 'dev-2026-02'

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y git rsync

      - name: Build binary
        run: odin build src/ -out:${{ matrix.artifact_name }}

      - name: Rename binary for release
        run: mv ${{ matrix.artifact_name }} chi-${{ matrix.suffix }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: chi-${{ matrix.suffix }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
